[workspace]
members = [
	'testsuite',
	'lain',
	'lain_derive',
]

[workspace.package]
version = "0.5.7"          
authors = ["Lain Devs", "AFLplusplus"]
edition = "2018"
homepage = "https://github.com/AFLplusplus/lain"
keywords = ["lain", "fuzzer", "mutator", "mutate", "mutation"]
license = "MIT"
